---
apiVersion: "batch/v1"
kind: "Job"
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    {{- if .Values.cleanup.deletePodsOnSuccess }}
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
    {{- end }}
spec:
  ttlSecondsAfterFinished: 7200
  backoffLimit: 0
  template:
    spec:
      restartPolicy: "OnFailure"
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
        - name: "{{ . }}"
        {{- end }}
      {{- end }}
      containers:
        - name: "migrate"
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}{{ if .Values.image.sha256 }}@sha256:{{ .Values.image.sha256 }}{{ else }}:{{ .Values.image.tag }}{{ end }}"
          command:
            - "/bin/bash"
            - "/app/docker/prod/migrate-db"
...
